fantasyland/fantasy-land

README.md, id.js
=> Rename Comonad method "from" to "extract"

implementations.md
<https://github.com/plaid/sanctuary>
=> implementations: add Sanctuary

README.md
This will aid navigation of the document.
=> readme: add section links

README.md
=> Use arrow functions in code snippets

id.js
#113 pointed out that I'd left this as the previous traverse implementation. This updates the example
=> not traverse, but sequence silly

README.md
Sorry didn't notice there is another image when submited #118 , and it was merged too fast ;)
=> Set dependencies.png's width/height

README.md, id.js, index.js, package.json
Implementation of idea discussed here https://github.com/fantasyland/fantasy-land/issues/92#issuecomment-172357516
=> Add index.js that exposes constants for method names

README.md
Static Land is not intended to be a competitor for Fantasy Land so I thought it might be OK to add the link. /cc @joneshf
=> Add a link to Static Land

.travis.yml, README.md, package.json
Tested that it works in my fork https://travis-ci.org/rpominov/fantasy-land/builds
After merging someone with write access will need to go to https://travis-ci.org/ and just turn it on.
=> Setup travis

laws/monad.js
=> laws/monad: fix leftIdentity

README.md
For consistency with other signatures.
=> Fix reduce signature to not use currying

id_test.js
This is the pay-off for taking arguments one at a time. :)
=> test: remove unnecessary lambdas

README.md
https://github.com/fantasyland/fantasy-laws/pull/1#discussion_r106814185
=> name Comonad laws

README.md
=> Add missing Ord link

README.md
=> Update Apply docs (#246)

README.md
Closes #262
Sorry, maybe it was not necessary duplicate the PR.
=> doc: add 0 arguments Function type constructor definition #262

README.md
fixes https://github.com/fantasyland/fantasy-land/issues/267
=> s/any/all in README.md

README.md
This order feels more natural to me.
=> flip operands in Semigroupoid associativity law to match Semigroup law

README.md
<https://github.com/fantasyland/fantasy-land/pull/272#issuecomment-336478899>
=> fix Group laws

implementations.md
Needs more robust testing but some integration testing like sequence, map, etc. all works fine - so I think it's okay to add for now :)
=> Add SodiumFRP

README.md
=> Clarify meaning of 42 :: Integer, Number

implementations.md
Related issue in purify: https://github.com/gigobyte/purify/issues/196
=> Add purify to list of implementations
