- README.md
It's visually confusing for Applicative named 'a' to call an identity function that also has a variable named 'a'.
> Clearer variable names in identity fn

- README.md
> Syntax fix for Applicative's derivation of map

- id.js
The comments in the Identity container are now in sync with the spec, making for less confusion.
See #111
> Fixed #111 - Corrected inconsistencies in id.js

- README.md
When someone comes to the project page via a #hash link they can end up at a wrong position. Because  after image loaded page height changes at scroll moves. This PR should fix that.
> Set logo width/height to prevent jumps of #hash links

- README.md
Array.prototype.concat flattens the argument if it is an array, so
concat with a single-element array here.
Hope I am not mistaken?
> Fix derived Foldable.toArray

- .gitignore
- README.md
- id.js
- id_test.js
- laws/applicative.js
- laws/apply.js
- laws/chain.js
- laws/comonad.js
- laws/extend.js
- laws/foldable.js
- laws/functor.js
- laws/monad.js
- laws/monoid.js
- laws/semigroup.js
- laws/setoid.js
- laws/traversable.js
- package.json
The motivation behind this is to allow any person wanting to implement
any structure that should conform to the specification will also have
the readme and more importantly the implementations of the laws.
The advantage of this as well is that any changes to the spec should be
reflected in the laws folder.
> Add the laws implementations

- README.md
See #128
Opening the PR to get this moving.
> Fix traversable laws

- README.md
Closes #132
Commit message:
> Derivations of FL methods are relevant to implementers of data types.
>
> Derivations of FL methods are irrelevant to implementers of functions which operate on values of these types, since the values must provide the relevant methods.
I'm not sure how `toArray` and `traverse` fit into the specification.
> derivations do not make certain methods optional

- README.md
@joneshf Pointed out that the Compose type as it currently implemented in the spec doesn't pass the Applicative laws. For instance `Compose.of(x => x).ap(Compose.of(1))` will blow up. 
I've also changed the letters that are used for variables and types to hopefully a bit more appropriate ones.
Checked that new code works fine in [Ramda REPL](http://ramdajs.com/repl/#?code=%0Afunction%20IdGenerator%28name%29%20%7B%0A%0A%20%20var%20Id%20%3D%20function%28a%29%20%7B%0A%20%20%20%20this.value%20%3D%20a%3B%0A%20%20%7D%3B%0A%0A%20%20Id.of%20%3D%20function%28a%29%20%7B%0A%20%20%20%20return%20new%20Id%28a%29%3B%0A%20%20%7D%3B%0A%0A%20%20Id.prototype.map%20%3D%20function%28f%29%20%7B%0A%20%20%20%20return%20Id.of%28f%28this.value%29%29%3B%0A%20%20%7D%3B%0A%0A%20%20Id.prototype.ap%20%3D%20function%28b% …
> Make Compose to be a proper Applicative

- README.md
- index.js
- laws/bifunctor.js
- laws/profunctor.js
A slight variation of the profunctor and bifunctor specs raised in #124, removing the mention of `lmap` and renaming `dimap` to `promap`.
> Profunctor and bifunctor specification

- README.md
Addresses #138
Throwing this up as a bit of a strawman, as there will no doubt be differing opinions around syntax.
I put forward the following suggestion:
```
sequence :: Apply f, Traversable t => t (f a) ~> (b -> f b) -> f (t a)
'------'    '--------------------'    '-----'    '-------------------'
'- method name     '- constraints     '- method target  '- method arguments
```
I'm also not sure whether an explanation of the syntax should be included in the spec or not.
> Add type signatures to spec

- index.js
Step 1 of #139
Is `FantasyLand` the best property name? Users are free to write `var FL = window.FantasyLand;` in their own code if a shorter name is desired.
> browser support

- README.md
- id.js
- laws/applicative.js
- laws/apply.js
- laws/traversable.js
See #50 and #144
This is a breaking change and we have two options how to do it:
1. Like any other changes that were done before (except they weren't breaking)
2. Add prefixes to method names (#122) and bump major version number
If we go with the first option there will be a period when some libraries already updated but some not, so they might not work well with each other. For example a code like this may stop working:
```js
import R from 'ramda'
import Foo from 'foo'
a = R.lift(x => y => x + y, Foo.of(1), Foo.of(2))
```
In this case users of libraries will have to freeze their dependencies' versions until all libs are updated.
If we do the second, a user of the libraries will be able to force one that already updated to work in `v0.2` mode, by installing `fantasy-land@0.2.1` instead of …
> Flip arguments order in ap

- README.md
For consistency with other signatures.
> Fix chainRec signature to not use currying

- bower.json
Step 2 of #139
Note that this only exposes __index.js__ since the other JavaScript files depend on fantasy-combinators which is not in the Bower registry.
> bower: add bower.json

- laws/functor.js
> laws/functor: fix composition

- README.md
We already have similar note for `of` method, but I figured we should add it for other methods as well.
See also https://github.com/fantasyland/fantasy-land/issues/85
> Enforce parametricity

- id.js
- id_test.js
- index.js
- laws/applicative.js
- laws/apply.js
- laws/bifunctor.js
- laws/chain.js
- laws/chainrec.js
- laws/comonad.js
- laws/extend.js
- laws/foldable.js
- laws/functor.js
- laws/monad.js
- laws/monoid.js
- laws/profunctor.js
- laws/semigroup.js
- laws/setoid.js
- laws/traversable.js
- package.json
Linting is hooked up to `npm test` so Travis will run `eslint` for us. :)
> lint: integrate ESLint

- README.md
- id.js
- id_test.js
- laws/applicative.js
- laws/chainrec.js
- laws/monoid.js
Closes #176
> ## Type representatives
>
> Certain behaviours are defined from the perspective of a member of a type. Other behaviours do not require a member. Thus certain algebras require a type to provide a value-level representative (with certain properties). The Identity type, for example, could provide `Id` as its type representative: `Id :: TypeRep Identity`.
>
> If a type provides a type representative, each member of the type must have a `constructor` property which is a reference to the type representative.
I imagine there are several things I neglected to update. Let me know if you think of one. :)
> require static methods to be defined on type representatives

- package.json
Using [xyz][1] to release new versions of this package will remove many sources of human error from the process. It will also make releasing new versions very convenient, as one will simply run one of the following commands:
```console
$ npm run-script release-major
```
```console
$ npm run-script release-minor
```
```console
$ npm run-script release-patch
```
This will:
1.  Verify that the current branch is `master`.
2.  Verify that the working directory contains no unstaged changes.
3.  Present a confirmation prompt.
4.  Verify that `npm test` exits successfully.
5.  Update the `"version"` field in __package.json__.
6.  Commit the change to __package.json__ with the message `Version X.Y.Z`.
7.  Create an annotated tag named `vX.Y.Z` pointing to the commit.
8.  Push the commit and the …
> release: integrate xyz

- id_test.js
- laws/functor.js
- laws/monad.js
> Fix id_test and argument order in laws

- README.md
- laws/monad.js
- laws/monoid.js
In Applicative we are using `A` but in monad and monoid we still use `m`.
in case of Monad one might think that we are accessing `of` on instance.
monoid law is technically correct but I think sticking to one way of doing thing is better so i have updated it as well.
> Use uppercase letters for TypeRep

- README.md
afaict this was a typo. very confusing for learners like me. :<
> traverse: Apply -> Applicative

- README.md
- laws/comonad.js
- test.js
Thank you for pointing out this inconsistency, @jlmorgan.
If Extend really *does* depend on Functor we should update the description of Extend rather than merge this pull request.
> update Extend and Comonad dependencies to match figure

- README.md
- internal/id.js
- internal/patch.js
- laws/traversable.js
- test.js
Closes #207
I intend to merge sanctuary-js/sanctuary-type-classes#28 regardless, but it would be nice to make this improvement here too. :)
> have traverse take a type representative rather than an "of" function

- README.md
Shouldn't that be `w` to be aligned with specifications below or am I missing something?
> Correct comonad value variable name

- README.md
> Added a section on "Type signature notation" in README.md

- README.md
In the rendered README, the word "<input-types>" is missing. This PR will render the word correctly in markdown.
> fix: add appropriate markdown to render missing word

- implementations.md
Ramda adjunct contains functional utils  for monadic types from monet, ramda-fantasy and contains reference implementation of Identity monad compliant with fantasy-land.
> docs(implementations.md): add ramda-adjunct

- implementations.md
Previously it mentioned Maybe, Result, Validation, Task, and Future as "FL-compatible Monads". Validation doesn't implement Monad and the other types implement other FL interfaces as well. FL-compatible types is a more generic (if vague-ish) description.
> Fixes Folktale description

- implementations.md
Monastic was made in response to https://github.com/fantasyland/fantasy-states
being archived, and as a learning exercise. It's tested for compliance with fantasy-laws.
> Add Monastic to the list of conformant implementations

- README.md
These changes make the document clearer but uglier. Clarity trumps beauty, in this context.
:thumbsup: / :thumbsdown: ?
> readme: use prefixed method names

- .eslintrc.json
- README.md
The default behaviour of [sanctuary-scripts][1] is to use [Transcribe][2] to generate __README.md__ from comments in source code. If the readme is to be maintained by hand, as is the case here, one should disable the default behaviour by including an empty `generate-readme` executable in the __scripts__ directory. I forgot to do so in #293, so __README.md__ was removed when I published v4.0.0.
This pull request reinstates __README.md__ and adds the missing executable to prevent the problem from happening again. I will merge this pull request then publish v4.0.1.
[1]: https://github.com/sanctuary-js/sanctuary-scripts
[2]: https://github.com/plaid/transcribe
> readme: reinstate readme and fix automated release workflow

- implementations.md
Zion is a functional programming library inspired by Haskell and Fantasy Land.
It provides some Haskell-like algebraic data-types and polymorphic functions against Fantasy Land algebraic structures.
> Added Zion

- package.json
The fantasy-land keys are currently not importable when using esmodules
available in node 12 and forward, these changes solve the problem.
The module field has been removed since it serves no purpose and is not
recognized by node. Exports field has been added accoding to the
official node js documentation:
https://nodejs.org/api/packages.html#packages_conditional_exports
Main field is kept for legacy suppoert of node versions 12 and earlier.
The types field has been removed since it is not needed. Typescript will
find the definitions anyway when using both import and require.
This should in theory not be breaking but it is difficult to know if any
use case or build tool relies on the undocumented conventions that
previoulsy existed in package.json.
> use correct fields for entry points in package.json
